- id: validate-flux
  name: validate Flux and Kustomize manifests
  description: "A script to validate Flux custom resources and Kustomize overlays."
  entry: ./scripts/validate-flux.sh
  language: script
  pass_filenames: false
  stages: [push]
- id: validate-eslint
  name: validate eslint
  description: "A script to validate eslint rules on Javascript and Typescript files."
  entry: ./scripts/validate-eslint.sh
  language: script
  stages: [commit]
- id: run-samplr
  name: generate sample .env files
  description: "A script to generate sample files."
  entry: ./scripts/samplr/run-samplr.sh
  language: script
  stages: [commit]
